# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(blank=True, db_column='roll_no', null=True),
        ),
    ]
